spring:
  jpa:
#    hibernate:
#      ddl-auto: create
    # 전 송 쿼 리 확 인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테 이 블 생 성 후 에 d a t a . s q l 실 행
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb #jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
